language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version 

  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed koneahmed/udagram-api-feed:v1
  - docker tag udagram-api-user koneahmed/udagram-api-user:v1
  - docker tag udagram-frontend koneahmed/udagram-frontend:v1
  - docker tag udagram-reverseproxy koneahmed/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD". | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push koneahmed/udagram-api-feed:v1
  - docker push koneahmed/udagram-api-user:v1
  - docker push koneahmed/udagram-frontend:v1
  - docker push koneahmed/udagram-reverseproxy:v1
